# Image base
FROM python:3.10

#Dependencies
WORKDIR /app

#Copy files
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

#Copy API code
COPY . .

#Port 8000 and FastAPI execution
EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]