version: "3.10"

services:
  backend:
    build: ./backend
    container_name: poetry-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: poetry-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
  
